dtype: bfloat16
flux_path: /home/users/astar/ares/qianhang/scratch/chengyou/hugging/Kontext
model:
  add_cond_attn: false
  add_cont_attn: false
  latent_lora: false
  union_cond_attn: true
train:
  accumulate_grad_batches: 1
  batch_size: 1
  dataloader_workers: 1
  gradient_checkpointing: true
  lora_config:
    init_lora_weights: gaussian
    lora_alpha: 4
    r: 4
    target_modules: (.*x_embedder|.*(?<!single_)transformer_blocks\.[0-9]+\.norm1\.linear|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_k|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_q|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_v|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_out\.0|.*(?<!single_)transformer_blocks\.[0-9]+\.ff\.net\.2|.*single_transformer_blocks\.[0-9]+\.norm\.linear|.*single_transformer_blocks\.[0-9]+\.proj_mlp|.*single_transformer_blocks\.[0-9]+\.proj_out|.*single_transformer_blocks\.[0-9]+\.attn.to_k|.*single_transformer_blocks\.[0-9]+\.attn.to_q|.*single_transformer_blocks\.[0-9]+\.attn.to_v|.*single_transformer_blocks\.[0-9]+\.attn.to_out)
  max_steps: -1
  optimizer:
    params:
      lr: 1
      safeguard_warmup: true
      use_bias_correction: true
      weight_decay: 0.01
    type: Prodigy
  sample_interval: 20
  save_interval: 5000
  save_path: runs
  wandb:
    project: DenseDiT
